### ISSUE TITLE
Virus detected.

### ISSUE THREAD

**Issue by sebastianfernandezgarcia** [showlab/computer_use_ootb#30]
Anti virus detects the app as virus and deletes it.

""Fast reverse proxy detected"

So the app does not work.

**Comment by h-siyuan** [comment]
It might be caused by the strict rule configured in your firewall, as this is the first case of such warning in our user feedback/we didn't encounter such warning in our testing. You can set the share flag to False in the app.py (in the last line share = False), but you will not be able to remotely control your computer using your other device, which is a great feature of Gradio.
